name: GitHub Actions Terraform Deployment
on:
  push:
    branches:
      - main
      
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS Credentials Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.ACCESSKEY }}
        aws-secret-access-key: ${{ secrets.SECRETKEY }}
        aws-region: us-east-1
    
    - name: Setup Terraform CLI    
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.1.9"

    - name: Terraform Init
      run: terraform init \
            -backend-config="bucket=${{ secrets.S3BUCKET }}" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=us-east-1" \
            -backend-config="profile=default"
