name: GitHub Actions Terraform Deployment
on:
  push:
    branches:
      - main
      
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS Credentials Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    
    - name: Setup Terraform CLI    
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.1.9"
        
    - name: Terraform Init
      run: terraform init